### ISSUE TITLE
服务端编译不通过

### ISSUE THREAD

**Issue by greezi** [xurunkang/QuickTouch#1]
clang: error: no such file or directory: '/Users/tudou/Library/Mobile Documents/com~apple~CloudDocs/QTProcessor.m'
clang: error: no input files

Xcode Version : 8.1 (8B62)

**Comment by LucasXu0** [comment]
我尝试 `git clone https://github.com/xurunkang/QuickTouch.git`和 直接 Download 最新的，都是没有问题的，请问你是下载最新版的吗？

**Comment by greezi** [comment]
刚重新clone过在编译。还是不行

**Comment by LucasXu0** [comment]
十分抱歉，现在已经修改了错误，原因是 Compile Sources 的目录错了，感谢你的反馈😊
